//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToeGameWPFClient.TicTacToeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Move", Namespace="http://schemas.datacontract.org/2004/07/TicTacToeGameService.Models")]
    [System.SerializableAttribute()]
    public partial class Move : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerStatus {
            get {
                return this.PlayerStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerStatusField, value) != true)) {
                    this.PlayerStatusField = value;
                    this.RaisePropertyChanged("PlayerStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicTacToeServiceReference.ITicTacToeGameContract", CallbackContract=typeof(TicTacToeGameWPFClient.TicTacToeServiceReference.ITicTacToeGameContractCallback))]
    public interface ITicTacToeGameContract {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Join")]
        void Join(string login, int sideSize);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Join")]
        System.Threading.Tasks.Task JoinAsync(string login, int sideSize);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Leave")]
        void Leave();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Leave")]
        System.Threading.Tasks.Task LeaveAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Move")]
        void Move([System.ServiceModel.MessageParameterAttribute(Name="move")] TicTacToeGameWPFClient.TicTacToeServiceReference.Move move1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Move")]
        System.Threading.Tasks.Task MoveAsync(TicTacToeGameWPFClient.TicTacToeServiceReference.Move move);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/ResetGame")]
        void ResetGame(int sideSize);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/ResetGame")]
        System.Threading.Tasks.Task ResetGameAsync(int sideSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicTacToeGameContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/PrintMove")]
        void PrintMove(TicTacToeGameWPFClient.TicTacToeServiceReference.Move move);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/DisableAllButtons")]
        void DisableAllButtons();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/DisableButton")]
        void DisableButton(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/CreateButtons")]
        void CreateButtons(int sideSize);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/PrintAllMove")]
        void PrintAllMove(System.Collections.Generic.List<TicTacToeGameWPFClient.TicTacToeServiceReference.Move> moves);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/PrintNameClients")]
        void PrintNameClients(System.Collections.Generic.List<string> users);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/SetStatus")]
        void SetStatus(string status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/Victory")]
        void Victory();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/VictoryResults")]
        void VictoryResults(string winnerStatus);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITicTacToeGameContract/SetMove")]
        void SetMove(bool IsMove);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicTacToeGameContractChannel : TicTacToeGameWPFClient.TicTacToeServiceReference.ITicTacToeGameContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicTacToeGameContractClient : System.ServiceModel.DuplexClientBase<TicTacToeGameWPFClient.TicTacToeServiceReference.ITicTacToeGameContract>, TicTacToeGameWPFClient.TicTacToeServiceReference.ITicTacToeGameContract {
        
        public TicTacToeGameContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TicTacToeGameContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TicTacToeGameContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicTacToeGameContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TicTacToeGameContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join(string login, int sideSize) {
            base.Channel.Join(login, sideSize);
        }
        
        public System.Threading.Tasks.Task JoinAsync(string login, int sideSize) {
            return base.Channel.JoinAsync(login, sideSize);
        }
        
        public void Leave() {
            base.Channel.Leave();
        }
        
        public System.Threading.Tasks.Task LeaveAsync() {
            return base.Channel.LeaveAsync();
        }
        
        public void Move(TicTacToeGameWPFClient.TicTacToeServiceReference.Move move1) {
            base.Channel.Move(move1);
        }
        
        public System.Threading.Tasks.Task MoveAsync(TicTacToeGameWPFClient.TicTacToeServiceReference.Move move) {
            return base.Channel.MoveAsync(move);
        }
        
        public void ResetGame(int sideSize) {
            base.Channel.ResetGame(sideSize);
        }
        
        public System.Threading.Tasks.Task ResetGameAsync(int sideSize) {
            return base.Channel.ResetGameAsync(sideSize);
        }
    }
}
